[2024-06-25T12:37:39.326+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: challenge_dag.extract_task manual__2024-06-25T12:37:36.969244+00:00 [queued]>
[2024-06-25T12:37:39.331+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: challenge_dag.extract_task manual__2024-06-25T12:37:36.969244+00:00 [queued]>
[2024-06-25T12:37:39.331+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-06-25T12:37:39.366+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): extract_task> on 2024-06-25 12:37:36.969244+00:00
[2024-06-25T12:37:39.373+0000] {standard_task_runner.py:57} INFO - Started process 45443 to run task
[2024-06-25T12:37:39.380+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'challenge_dag', 'extract_task', 'manual__2024-06-25T12:37:36.969244+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/challange_dag.py', '--cfg-path', '/tmp/tmp5_aqpmxw']
[2024-06-25T12:37:39.382+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask extract_task
[2024-06-25T12:37:39.443+0000] {task_command.py:410} INFO - Running <TaskInstance: challenge_dag.extract_task manual__2024-06-25T12:37:36.969244+00:00 [running]> on host codespaces-e400ad
[2024-06-25T12:37:39.540+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='challenge_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T12:37:36.969244+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-25T12:37:36.969244+00:00'
[2024-06-25T12:37:39.542+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-25T12:37:39.542+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wget -c https://raw.githubusercontent.com/vinooganesh/hands-on-introduction-data-engineering-4395021-data-files/main/constituents.csv -O /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-extract-data.csv']
[2024-06-25T12:37:39.551+0000] {subprocess.py:86} INFO - Output:
[2024-06-25T12:37:39.555+0000] {subprocess.py:93} INFO - --2024-06-25 12:37:39--  https://raw.githubusercontent.com/vinooganesh/hands-on-introduction-data-engineering-4395021-data-files/main/constituents.csv
[2024-06-25T12:37:39.557+0000] {subprocess.py:93} INFO - Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
[2024-06-25T12:37:39.563+0000] {subprocess.py:93} INFO - Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
[2024-06-25T12:37:39.607+0000] {subprocess.py:93} INFO - HTTP request sent, awaiting response... 404 Not Found
[2024-06-25T12:37:39.608+0000] {subprocess.py:93} INFO - 2024-06-25 12:37:39 ERROR 404: Not Found.
[2024-06-25T12:37:39.608+0000] {subprocess.py:93} INFO - 
[2024-06-25T12:37:39.609+0000] {subprocess.py:97} INFO - Command exited with return code 8
[2024-06-25T12:37:39.614+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 8.
[2024-06-25T12:37:39.616+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=challenge_dag, task_id=extract_task, execution_date=20240625T123736, start_date=20240625T123739, end_date=20240625T123739
[2024-06-25T12:37:39.659+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 19 for task extract_task (Bash command failed. The command returned a non-zero exit code 8.; 45443)
[2024-06-25T12:37:39.670+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-06-25T12:37:39.685+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
